
/* This file was generated by idltool 53.6. Do not edit */

#include "amosextension_vectors.h"

STATIC CONST APTR main_v1_vectors[] =
{
    _amosextension_Obtain,
    _amosextension_Release,
    NULL,
    NULL,
    _amosextension_OpenExtension,
    _amosextension_CloseExtension,
    _amosextension_GetCommandByName,
    _amosextension_GetCommandByToken,
    _amosextension_FreeTokenInfo,
    (APTR)-1
};

