/*
**	$Id$
**	Generated by IDLTool 53.6
**	Do not edit
**
**	AutoInit stub for amosextension
**
**	Copyright (c) 2010 LiveForIt Software.
**	MIT License.
*/

#include <exec/types.h>
#include <libraries/amosextension.h>

#include <interfaces/amosextension.h>
#include <proto/exec.h>
#include <assert.h>

struct amosextensionIFace * Iamosextension = NULL;
static struct Library * __amosExtensionBase;
static struct amosextensionIFace * __Iamosextension;

/****************************************************************************/

extern struct Library * amosExtensionBase;

/****************************************************************************/

void amosextension_main_constructor(void)
{
    if (amosExtensionBase == NULL) /* Library base is NULL, we need to open it */
    {
        /* We were called before the base constructor.
         * This means we will be called _after_ the base destructor.
         * So we cant drop the interface _after_ closing the last library base,
         * we just open the library here which ensures that.
         */
        __amosExtensionBase = amosExtensionBase = (struct Library *)IExec->OpenLibrary("amosextension.library", 0L);
        assert(amosExtensionBase != NULL);
    }

    __Iamosextension = Iamosextension = (struct amosextensionIFace *)IExec->GetInterface((struct Library *)amosExtensionBase, "main", 1, NULL);
    assert(Iamosextension != NULL);
}
__attribute__((section(".ctors.zzzy"))) static void
(*amosextension_main_constructor_ptr)(void) USED = amosextension_main_constructor;

/****************************************************************************/

void amosextension_main_destructor(void)
{
    if (__Iamosextension)
    {
        IExec->DropInterface ((struct Interface *)__Iamosextension);
    }
    if (__amosExtensionBase)
    {
        IExec->CloseLibrary((struct Library *)__amosExtensionBase);
    }
}
__attribute__((section(".dtors.zzzy"))) static void
(*amosextension_main_destructor_ptr)(void) USED = amosextension_main_destructor;

/****************************************************************************/

