/*
**	$Id$
**	Generated by IDLTool 53.6
**	Do not edit
**
**	AutoInit stub for amosextension
**
**	Copyright (c) 2010 LiveForIt Software.
**	MIT License.
*/

#include <exec/types.h>
#include <libraries/amosextension.h>

#include <interfaces/amosextension.h>
#include <proto/exec.h>
#include <assert.h>

/****************************************************************************/

struct Library * amosExtensionBase = NULL;
static struct Library * __amosExtensionBase;

/****************************************************************************/

void amosextension_base_constructor(void)
{
    if (amosExtensionBase != NULL)
    {
        return; /* Someone was quicker, e.g. an interface constructor */
    }
    __amosExtensionBase = amosExtensionBase = (struct Library *)IExec->OpenLibrary("amosextension.library", 0L);
    assert(amosExtensionBase != NULL);
}
__attribute__((section(".ctors.zzzz"))) static void
(*amosextension_base_constructor_ptr)(void) USED = amosextension_base_constructor;

/****************************************************************************/

void amosextension_base_destructor(void)
{
    if (__amosExtensionBase)
    {
        IExec->CloseLibrary((struct Library *)__amosExtensionBase);
    }
}
__attribute__((section(".dtors.zzzz"))) static void
(*amosextension_base_destructor_ptr)(void) USED = amosextension_base_destructor;

/****************************************************************************/

