#ifndef AMOSEXTENSION_INTERFACE_DEF_H
#define AMOSEXTENSION_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.6.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_AMOSEXTENSION_H
#include <libraries/amosextension.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct amosextensionIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct amosextensionIFace *Self);
	ULONG APICALL (*Release)(struct amosextensionIFace *Self);
	void APICALL (*Expunge)(struct amosextensionIFace *Self);
	struct Interface * APICALL (*Clone)(struct amosextensionIFace *Self);
	struct AmosExtension * APICALL (*OpenExtension)(struct amosextensionIFace *Self, char * name);
	void APICALL (*CloseExtension)(struct amosextensionIFace *Self, struct AmosExtension * extension);
	void APICALL (*GetCommandByName)(struct amosextensionIFace *Self, char * name);
	void APICALL (*GetCommandByToken)(struct amosextensionIFace *Self, short token);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* AMOSEXTENSION_INTERFACE_DEF_H */
