#ifndef AMOSEXTENSION_INTERFACE_DEF_H
#define AMOSEXTENSION_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.6.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_AMOSEXTENSION_H
#include <libraries/amosextension.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct AmosExtensionIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct AmosExtensionIFace *Self);
	ULONG APICALL (*Release)(struct AmosExtensionIFace *Self);
	void APICALL (*Expunge)(struct AmosExtensionIFace *Self);
	struct Interface * APICALL (*Clone)(struct AmosExtensionIFace *Self);
	struct extension * APICALL (*OpenExtension)(struct AmosExtensionIFace *Self, char * name);
	void APICALL (*CloseExtension)(struct AmosExtensionIFace *Self, struct extension * extension);
	unsigned int APICALL (*GetCommandByName)(struct AmosExtensionIFace *Self, char * name);
	unsigned int APICALL (*GetCommandByToken)(struct AmosExtensionIFace *Self, unsigned short token);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* AMOSEXTENSION_INTERFACE_DEF_H */
