
/* This file was generated by idltool 53.6. Do not edit */

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_AMOSEXTENSION_H
#include <libraries/amosextension.h>
#endif

extern ULONG                VARARGS68K _amosextension_Obtain(struct AmosExtensionIFace *);
extern ULONG                VARARGS68K _amosextension_Release(struct AmosExtensionIFace *);
extern struct extension *   VARARGS68K _amosextension_OpenExtension(struct AmosExtensionIFace *, char * name);
extern void                 VARARGS68K _amosextension_CloseExtension(struct AmosExtensionIFace *, struct extension * extension);
extern struct TokenInfo *   VARARGS68K _amosextension_GetCommandByName(struct AmosExtensionIFace *, struct extension * ext, char * name);
extern struct TokenInfo *   VARARGS68K _amosextension_GetCommandByToken(struct AmosExtensionIFace *, struct extension * ext, unsigned short token);
extern void                 VARARGS68K _amosextension_FreeTokenInfo(struct AmosExtensionIFace *, struct TokenInfo * info);
extern char *               VARARGS68K _amosextension_GetExtensionName(struct AmosExtensionIFace *, struct extension * ext);
extern struct ExtensionDescriptor * VARARGS68K _amosextension_FirstExtensionItem(struct AmosExtensionIFace *, struct extension * ext);
extern struct ExtensionDescriptor * VARARGS68K _amosextension_NextExtensionItem(struct AmosExtensionIFace *, struct ExtensionDescriptor * extension_descriptor);
extern void                 VARARGS68K _amosextension_CloseExtensionDescriptor(struct AmosExtensionIFace *, struct ExtensionDescriptor * extension_descriptor);
extern char *               VARARGS68K _amosextension_GetExtensionNameByToken(struct AmosExtensionIFace *, struct extension * ext, unsigned short token);
