#ifndef INLINE4_AMOSEXTENSION_H
#define INLINE4_AMOSEXTENSION_H

/*
** This file was auto generated by idltool 53.6.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_AMOSEXTENSION_H
#include <libraries/amosextension.h>
#endif
#include <interfaces/amosextension.h>

/* Inline macros for Interface "main" */
#define OpenExtension(name) IAmosExtension->OpenExtension((name)) 
#define CloseExtension(extension) IAmosExtension->CloseExtension((extension)) 
#define GetCommandByName(name) IAmosExtension->GetCommandByName((name)) 
#define GetCommandByToken(token) IAmosExtension->GetCommandByToken((token)) 

#endif /* INLINE4_AMOSEXTENSION_H */
